### ISSUE TITLE
Ability to select a subset tests to run?

### ISSUE THREAD

**Issue by rtoy** [spotify/web-audio-bench#2]
It would be nice if there were some way to select a subset of tests to be run so that I don't have to run the entire test bench to see how performance has changed for some specific tests.

This is useful for testing some targeted optimizations, but of course, the entire testbench still needs to be run as a sanity check that the optimization hasn't inadvertently degraded performance in other areas.

**Comment by bjornm** [comment]
Okay, I've added the ability to select which tests to run. Note that the benchmark score will only be calculated if all tests are selected.
